const ITEMS = [
{id:"p135-q23",title:"Central Park 第 23 题",meta:"KET Part 4 · p.135",prompt:'The park is also very <span class="blank">23</span> with people who like sport.',options:[{key:"A",text:"A beautiful"},{key:"B",text:"B popular"},{key:"C",text:"C big"}],answer:"B",fill:"popular",ok:"The park is popular with people who like sport.",bad:"空格后是 with people，只能填 popular。",note:"<p>原句：The park is also very 23 with people who like sport.</p><p>书上 A、C 都圈过，在好看 / 大 / 受欢迎之间犹豫。</p><p><b>为什么是 popular？</b>固定搭配 be <u>popular with somebody</u> = 受某类人欢迎。后面已经是 with people，三个词里只有 popular 能接 with。</p><p>beautiful 可以形容公园好看，不能说 beautiful with people。</p><p>big 可以形容公园大，也不能说 big with people。</p><p>整页也可一起记：be known by / visit each year / many + 复数 / different kinds / be used for。</p>",photo:"photos/p135-central-park.jpg"},
{id:"mail1-q27",title:"Jerry 邮件 第 27 题 from",meta:"KET Part 5 · 生日礼物",prompt:'I got some good presents <span class="blank">27</span> my parents too.',options:[{key:"with",text:"with"},{key:"from",text:"from"},{key:"by",text:"by"}],answer:"from",fill:"from",ok:"presents from my parents = 父母给的礼物。",bad:"和父母在一起才用 with；礼物是谁给的用 from。",note:"<p>书上先写 with，后改 from。</p><p><b>from somebody</b> = 来自某人。presents from my parents。</p><p>with 是「和……在一起」，不是这句要说的。</p><p>东西是谁给的 → from。</p>",photo:"photos/email-jerry-bill.jpg"},
{id:"mail1-q28",title:"Jerry 邮件 第 28 题 than",meta:"KET Part 5 · 最容易混",prompt:"It's bigger <span class=\"blank\">28</span> my old one.",options:[{key:"of",text:"of"},{key:"then",text:"then"},{key:"than",text:"than"}],answer:"than",fill:"than",ok:"bigger than = 比旧的那台更大。",bad:"than 才是「比」。then 是然后，of 不能跟 bigger。",note:"<p>书上先写 of，红笔又写 then，两个都不对。</p><p><b>than</b> = 比。比较级后面固定接 than：bigger than / older than / cheaper than。</p><p><b>then</b> 读音像，意思是「然后」。</p><p><b>of</b> 是「……的」，不能说 bigger of。</p><p>看到 bigger / older / more，后面先想 than。</p>",photo:"photos/email-jerry-bill.jpg"},
{id:"mail1-q29",title:"Jerry 邮件 第 29 题 on",meta:"KET Part 5",prompt:"it's got a really cool picture <span class=\"blank\">29</span> the top.",options:[{key:"in",text:"in"},{key:"on",text:"on"},{key:"at",text:"at"}],answer:"on",fill:"on",ok:"a picture on the top。",bad:"在顶部用 on the top，不是 in。",note:"<p>书上先写 in，后改 on。</p><p><b>on the top</b> = 在顶部（贴在/印在上面）。电脑盖子上有图案，用 on。</p><p><b>in</b> 是在内部：in the box。顶部表面不用 in。</p><p>同类：a stamp on the envelope；a logo on the T-shirt。</p>",photo:"photos/email-jerry-bill.jpg"},
{id:"p141-q22",title:"Holidays 第 22 题 cost",meta:"KET Part 4 · p.141",prompt:"They didn't <span class=\"blank\">22</span> much, and people didn't need to travel very far.",options:[{key:"A",text:"A spend"},{key:"B",text:"B cost"},{key:"C",text:"C have"}],answer:"B",fill:"cost",ok:"They didn't cost much = 营地不贵。",bad:"spend 主语必须是人。They = holiday camps。",note:"<p>上文 holiday camps became popular. They didn't 22 much.</p><p>书上 spend 和 cost 都圈了。</p><p>主语 They 指 camps，是东西不是人。</p><p><b>cost</b>：东西花多少钱。The camps didn't cost much.</p><p><b>spend</b>：人花钱。People didn't spend much money.</p><p>口诀：人 spend，东西 cost。</p>",photo:"photos/p141-holidays.jpg"},
{id:"p141-q23",title:"Holidays 第 23 题 much",meta:"KET Part 4 · p.141",prompt:"it was <span class=\"blank\">23</span> cheaper to fly than ever before.",options:[{key:"A",text:"A many"},{key:"B",text:"B much"},{key:"C",text:"C more"}],answer:"B",fill:"much",ok:"much cheaper = 便宜得多。",bad:"many cheaper 错；more cheaper 是双重比较级。",note:"<p>书上 many 和 much 都圈了。</p><p><b>much + 比较级</b>：much cheaper / much bigger。</p><p>many 后面接可数复数，不能 many cheaper。</p><p>more cheaper 错，cheaper 已经是比较级。</p>",photo:"photos/p141-holidays.jpg"},
{id:"p141-q24",title:"Holidays 第 24 题 countries",meta:"KET Part 4 · p.141",prompt:"travel to other <span class=\"blank\">24</span> for the first time.",options:[{key:"A",text:"A countries"},{key:"B",text:"B cities"},{key:"C",text:"C villages"}],answer:"A",fill:"countries",ok:"机票便宜了，第一次飞到别的国家。",bad:"cities / villages 和坐飞机第一次出国对不上。",note:"<p>1980s 坐飞机变便宜，所以第一次能去 other countries。</p><p>英国人本来就能去本国海边小城，不必等机票变便宜。</p>",photo:"photos/p141-holidays.jpg"},
{id:"hosp-q25",title:"住院邮件 第 25 题 down",meta:"KET Part 5 · Fiona / Marry",prompt:"He fell <span class=\"blank\">25</span> the stairs yesterday.",options:[{key:"in",text:"in"},{key:"down",text:"down"},{key:"off",text:"off"}],answer:"down",fill:"down",ok:"fall down the stairs。",bad:"不是 fall in the stairs。",note:"<p>书上先写 in，改成 down。</p><p>固定：<b>fall down the stairs</b> = 从楼梯摔下去。</p>",photo:"photos/email-gavin-hospital.jpg"},
{id:"hosp-q27",title:"住院邮件 第 27 题 because",meta:"KET Part 5",prompt:"That's good <span class=\"blank\">27</span> he doesn't like homework!",options:[{key:"idea",text:"idea"},{key:"because",text:"because"},{key:"so",text:"so"}],answer:"because",fill:"because",ok:"That's good because he doesn't like homework.",bad:"idea 不能填。so 会把因果写反。",note:"<p>摔断腿要在家五个月。半开玩笑：正好他不爱写作业。</p><p><b>because</b> 接原因。idea 是名词，空格要连后面那句话，必须是连词。</p><p>so 是「所以」，方向反了。第 26 空 broken his leg so he needed to stay home 才用 so。</p>",photo:"photos/email-gavin-hospital.jpg"},
{id:"hosp-q30",title:"住院邮件 第 30 题 herself",meta:"KET Part 5",prompt:"my mum cut <span class=\"blank\">30</span> when she was making dinner",options:[{key:"it",text:"it"},{key:"herself",text:"herself"},{key:"her",text:"her"}],answer:"herself",fill:"herself",ok:"cut herself = 妈妈切到自己。",bad:"cut it 没说切到谁。cut her 像切到另一个人。",note:"<p>书上先写 it，后改 herself。</p><p>主语 mum，受伤也是自己 → <b>herself</b>。</p><p>I cut myself；he cut himself；she cut herself。</p>",photo:"photos/email-gavin-hospital.jpg"},
{id:"dol-q19",title:"Dolphin Hero 第 19 题 push",meta:"KET Part 4 · p.147",prompt:"tried to <span class=\"blank\">19</span> the whales back out to sea",options:[{key:"A",text:"A pull"},{key:"B",text:"B push"},{key:"C",text:"C call"}],answer:"B",fill:"push",ok:"push the whales back out to sea。",bad:"pull 能想，搭配是 push back out。",note:"<p>鲸搁浅在沙滩，把它们从沙滩<b>推回</b>海里：push ... back out to sea。</p><p>call the whales 救不了搁浅。</p>",photo:"photos/p147-dolphin.jpg"},
{id:"dol-q20",title:"Dolphin Hero 第 20 题 tired",meta:"KET Part 4 · p.147",prompt:"They were getting <span class=\"blank\">20</span> and I was afraid they were going to die",options:[{key:"A",text:"A cold"},{key:"B",text:"B warm"},{key:"C",text:"C tired"}],answer:"C",fill:"tired",ok:"getting tired，才怕它们死。",bad:"cold 不如 tired 紧；warm 更不对。",note:"<p>鲸反复被送回海又游回沙滩，会越来越累 getting tired，救援才怕它们死。</p>",photo:"photos/p147-dolphin.jpg"},
{id:"dol-q22",title:"Dolphin Hero 第 22 题 straight",meta:"KET Part 4 · p.147",prompt:"She came <span class=\"blank\">22</span> to us",options:[{key:"A",text:"A left"},{key:"B",text:"B right"},{key:"C",text:"C straight"}],answer:"C",fill:"straight",ok:"came straight to us = 径直游过来。",bad:"不能说 came left to us。",note:"<p><b>come straight to somebody</b> = 径直过来。</p><p>left / right 要说 turn left，不能 came left to us。</p>",photo:"photos/p147-dolphin.jpg"},
{id:"job-q25",title:"兼职邮件 第 25 题 as",meta:"KET Part 5 · Jessie / Amanda",prompt:"I'm working <span class=\"blank\">25</span> a shop assistant in a dessert shop!",options:[{key:"as",text:"as"},{key:"for",text:"for"},{key:"at",text:"at"}],answer:"as",fill:"as",ok:"work as a shop assistant = 当店员。",bad:"work for 后面是公司或人。",note:"<p>页脚口诀：</p><p><b>work as + 职业</b>：work as a shop assistant / teacher</p><p><b>work for + 公司或人</b>：work for a shop</p><p>空格后是 a shop assistant（职位），所以 as。</p>",photo:"photos/email-jessie-job.jpg"},
{id:"job-q26",title:"兼职邮件 第 26 题 from",meta:"KET Part 5",prompt:"I work every afternoon <span class=\"blank\">26</span> five o'clock to nine o'clock",options:[{key:"from",text:"from"},{key:"at",text:"at"},{key:"in",text:"in"}],answer:"from",fill:"from",ok:"from five to nine。",bad:"at five o'clock to nine 不对。红笔 at 不要改回去。",note:"<p>固定：<b>from A to B</b> = 从……到……。</p><p>at five o'clock 只表示五点这个时刻，不能再接 to nine 当时间段。</p><p>保持 from，不要改成 at。</p>",photo:"photos/email-jessie-job.jpg"}
];
const CARDS = [["受……欢迎","popular with","be popular with people"],["比","than","bigger than · 不是 then / of"],["礼物来自谁","from","presents from my parents"],["在顶部","on the top","不是 in"],["东西花费","cost","人用 spend"],["便宜得多","much cheaper","不是 more cheaper"],["出国","other countries","fly to other countries"],["摔楼梯","fall down the stairs","不是 in"],["切到自己","cut herself","she herself"],["推回海里","push back out to sea","whales"],["越来越累","getting tired","going to die"],["径直过来","come straight to","came straight to us"],["担任某职","work as","shop assistant"],["为公司干","work for","work for a shop"],["从到","from ... to","from five to nine"]];
