const ITEMS = [
  {id:"p135-q23",title:"Central Park 第 23 题",meta:"KET Part 4 · p.135",prompt:'The park is also very <span class="blank">23</span> with people who like sport.',options:[{key:"A",text:"A beautiful"},{key:"B",text:"B popular"},{key:"C",text:"C big"}],answer:"B",fill:"popular",ok:"popular with people = 受欢迎。",bad:"空格后是 with people，用 popular with。",note:"<p>固定搭配：be <u>popular with</u> somebody。beautiful / big 不能接 with people。</p>",photo:"photos/p135-central-park.jpg"},
  {id:"mail1-q27",title:"Jerry 邮件 27 from",meta:"KET Part 5",prompt:'presents <span class="blank">27</span> my parents',options:[{key:"with",text:"with"},{key:"from",text:"from"},{key:"by",text:"by"}],answer:"from",fill:"from",ok:"presents from my parents。",bad:"礼物来源用 from。",note:"<p>东西是谁给的 → from。</p>",photo:"photos/email-jerry-bill.jpg"},
  {id:"mail1-q28",title:"Jerry 邮件 28 than",meta:"KET Part 5",prompt:"bigger <span class=\"blank\">28</span> my old one",options:[{key:"of",text:"of"},{key:"then",text:"then"},{key:"than",text:"than"}],answer:"than",fill:"than",ok:"bigger than。",bad:"than 才是比，then 是然后。",note:"<p>比较级后接 than。</p>",photo:"photos/email-jerry-bill.jpg"},
  {id:"mail1-q29",title:"Jerry 邮件 29 on",meta:"KET Part 5",prompt:"picture <span class=\"blank\">29</span> the top",options:[{key:"in",text:"in"},{key:"on",text:"on"},{key:"at",text:"at"}],answer:"on",fill:"on",ok:"on the top。",bad:"不是 in。",note:"<p>on the top。</p>",photo:"photos/email-jerry-bill.jpg"},
  {id:"p141-q22",title:"Holidays 22 cost",meta:"p.141",prompt:"They didn't <span class=\"blank\">22</span> much.",options:[{key:"A",text:"A spend"},{key:"B",text:"B cost"},{key:"C",text:"C have"}],answer:"B",fill:"cost",ok:"didn't cost much。",bad:"spend 主语是人。",note:"<p>营地作主语用 cost。</p>",photo:"photos/p141-holidays.jpg"},
  {id:"p141-q23",title:"Holidays 23 much",meta:"p.141",prompt:"<span class=\"blank\">23</span> cheaper to fly",options:[{key:"A",text:"A many"},{key:"B",text:"B much"},{key:"C",text:"C more"}],answer:"B",fill:"much",ok:"much cheaper。",bad:"不是 more cheaper。",note:"<p>much + 比较级。</p>",photo:"photos/p141-holidays.jpg"},
  {id:"p141-q24",title:"Holidays 24 countries",meta:"p.141",prompt:"other <span class=\"blank\">24</span>",options:[{key:"A",text:"A countries"},{key:"B",text:"B cities"},{key:"C",text:"C villages"}],answer:"A",fill:"countries",ok:"other countries。",bad:"不是 cities。",note:"<p>飞机去别的国家。</p>",photo:"photos/p141-holidays.jpg"},
  {id:"hosp-q25",title:"住院 25 down",meta:"Part 5",prompt:"fell <span class=\"blank\">25</span> the stairs",options:[{key:"in",text:"in"},{key:"down",text:"down"},{key:"off",text:"off"}],answer:"down",fill:"down",ok:"fall down the stairs。",bad:"不是 in。",note:"<p>fall down the stairs。</p>",photo:"photos/email-gavin-hospital.jpg"},
  {id:"hosp-q27",title:"住院 27 because",meta:"Part 5",prompt:"That's good <span class=\"blank\">27</span> he doesn't like homework",options:[{key:"idea",text:"idea"},{key:"because",text:"because"},{key:"so",text:"so"}],answer:"because",fill:"because",ok:"because。",bad:"不是 idea。",note:"<p>That's good because...</p>",photo:"photos/email-gavin-hospital.jpg"},
  {id:"hosp-q30",title:"住院 30 herself",meta:"Part 5",prompt:"cut <span class=\"blank\">30</span>",options:[{key:"it",text:"it"},{key:"herself",text:"herself"},{key:"her",text:"her"}],answer:"herself",fill:"herself",ok:"cut herself。",bad:"不是 it。",note:"<p>cut herself。</p>",photo:"photos/email-gavin-hospital.jpg"},
  {id:"dol-q19",title:"Dolphin 19 push",meta:"p.147",prompt:"<span class=\"blank\">19</span> the whales back out to sea",options:[{key:"A",text:"A pull"},{key:"B",text:"B push"},{key:"C",text:"C call"}],answer:"B",fill:"push",ok:"push back out。",bad:"不是 pull。",note:"<p>push back out to sea。</p>",photo:"photos/p147-dolphin.jpg"},
  {id:"dol-q20",title:"Dolphin 20 tired",meta:"p.147",prompt:"getting <span class=\"blank\">20</span>",options:[{key:"A",text:"A cold"},{key:"B",text:"B warm"},{key:"C",text:"C tired"}],answer:"C",fill:"tired",ok:"tired。",bad:"不是 cold。",note:"<p>getting tired。</p>",photo:"photos/p147-dolphin.jpg"},
  {id:"dol-q22",title:"Dolphin 22 straight",meta:"p.147",prompt:"came <span class=\"blank\">22</span> to us",options:[{key:"A",text:"A left"},{key:"B",text:"B right"},{key:"C",text:"C straight"}],answer:"C",fill:"straight",ok:"straight。",bad:"不是 left。",note:"<p>come straight to。</p>",photo:"photos/p147-dolphin.jpg"},
  {id:"job-q25",title:"兼职 25 as",meta:"Part 5",prompt:"working <span class=\"blank\">25</span> a shop assistant",options:[{key:"as",text:"as"},{key:"for",text:"for"},{key:"at",text:"at"}],answer:"as",fill:"as",ok:"work as + 职业。",bad:"for 是公司。",note:"<p>work as + 职业；work for + 公司</p>",photo:"photos/email-jessie-job.jpg"},
  {id:"job-q26",title:"兼职 26 from",meta:"Part 5",prompt:"<span class=\"blank\">26</span> five o'clock to nine",options:[{key:"from",text:"from"},{key:"at",text:"at"},{key:"in",text:"in"}],answer:"from",fill:"from",ok:"from five to nine。",bad:"不是 at。",note:"<p>from A to B</p>",photo:"photos/email-jessie-job.jpg"}
];
const CARDS = [["受欢迎","popular with","popular with people"],["比","than","bigger than"],["来自","from","presents from"],["花费","cost","didn't cost much"],["便宜得多","much cheaper","not more cheaper"],["摔楼梯","fall down the stairs","not in"],["切到自己","cut herself","reflexive"],["推回海里","push back out","dolphins"],["径直","straight","came straight to us"],["担任","work as","shop assistant"],["从到","from to","from five to nine"]];
